pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        //Deploy to Staging Environmnet
        stage('Deploy in Staging Environment'){
            steps{
                build job: 'Deploy in Staging Environment'

            }           
        }

        //Delayed Deployment to PRODUCTION Environmnet
        stage('Deploy to Production'{
            steps{
                timeout (time: 5, unit:'DAYS' ){
                    input message: "Approve PRODUCTION Deployment"
                }

                build job: "deploy_application_production"

            }
        }
        
    }
}